framework:
    cache:
        app: cache.adapter.filesystem
        
        pools:
            cache.kanban_boards:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600 # 1 hour
            cache.kanban_user_data:
                adapter: cache.adapter.filesystem  
                default_lifetime: 1800 # 30 minutes
            cache.kanban_statistics:
                adapter: cache.adapter.filesystem
                default_lifetime: 7200 # 2 hours