# Enable stateless CSRF protection for forms and logins/logouts
framework:
    csrf_protection: ~
    form:
        csrf_protection: true
#            token_id: submit


#    csrf_protection:
#        stateless_token_ids:
#            - submit
#            - authenticate
#            - logout
