controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
chrome_devtools:
    path: /.well-known/appspecific/com.chrome.devtools.json
    methods: [GET]
    defaults:
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction'
        template: 'empty.json.twig'