parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'

    App\Service\CacheService:
        arguments:
            $cache: '@cache.app'
    
    App\Service\KanbanService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $boardRepository: '@App\Repository\BoardRepository'
            $colRepository: '@App\Repository\ColRepository'
            $taskRepository: '@App\Repository\TaskRepository'
            $cacheService: '@App\Service\CacheService'
            $eventDispatcher: '@event_dispatcher'
    
    App\Service\PerformanceMonitoringService:
        arguments:
            $logger: '@logger'
            $stopwatch: '@debug.stopwatch'
    
    App\EventListener\CacheInvalidationListener: ~

    App\Repository\BoardRepository: ~
    App\Repository\ColRepository: ~
    App\Repository\TaskRepository: ~
    App\Repository\UserRepository: ~